class HomeVM {
  static List<String> brands = [
    'Almay',
    'Alva',
    'Anna sui',
    'Annabelle',
    'Benefit',
    'Boosh',
    'Burt\'s bees',
    'Butter london',
    'Cest moi',
    'Cargo cosmetics',
    'China glaze',
    'Clinique',
    'Coastal classic creation',
    'Colourpop',
    'Covergirl',
    'Dalish',
    'Deciem',
    'Dior',
    'Dr. hauschka',
    'E.l.f.',
    'Essie',
    'Fenty',
    'Glossier',
    'Green people',
    'Iman',
    'L\'oreal',
    'Lotus cosmetics usa',
    'Maia\'s mineral galaxy',
    'Marcelle',
    'Marienatie',
    'Maybelline',
    'Milani',
    'Mineral fusion',
    'Misa',
    'Mistura',
    'Moov',
    'Nudus',
    'Nyx',
    'Orly',
    'Pacifica',
    'Penny lane organics',
    'Physicians formula',
    'Piggy paint',
    'Pure anada',
    'Rejuva minerals',
    'Revlon',
    'Sally b\'s skin yummies',
    'Salon perfect',
    'Sante',
    'Sinful colours',
    'Smashbox',
    'Stila',
    'Suncoat',
    'W3llpeople',
    'Wet n wild',
    'Zorah',
    'Zorah biocosmetiques'
  ];
  static List<String> categories = [
    'Blush',
    'Bronzer',
    'Eyebrow',
    'Eyeliner',
    'Eyeshadow',
    'Foundation',
    'Lip liner',
    'Lipstick',
    'Mascara',
    'Nail polish'
  ];
}
